### PR TITLE
Feat/clicks

### PR DESCRIPTION
**Pull request by mabrsweeney**
Hey @seanlangbrown, could you review my code.

I added two new additions to the component:
1.  When the city is clicked on the screen will scroll to show the map, similar to the Airbnb page.
2. When the host's name is clicked on a request to the server is sent to retrieve other experiences by that host. At the moment this only logs the array of experiences, but can be later used if we implement a list page for the experiences.  

Thanks!

### CODE REVIEW

**Review by seanlangbrown — COMMENTED** [review]
This all looks good. Your variable names are descriptive and style is nice.
One suggestion about server/server.js at line 49:
There is the possibility of an error occurring with the Detail.findOneAndUpdate operation.  I don't how findOneAndUpdate handles errors, but I would look into this, because if an error is thrown, it could require a server restart and shut down the server.

**Comment by mabrsweeney** [comment]
Hey, @seanlangbrown thanks for the input. Just fixed that and there are some additional changes I had to make to satisfy my linter, so you can just ignore those!

Thanks!

**Review by seanlangbrown — COMMENTED** [review]
Looks good... do you merge or do I?

**Comment by mabrsweeney** [comment]
I do!

**Pull request merged**
